# Pages configuration
name = "natalie-winters-prod-this"  # Primary project name (production)
compatibility_date = "2024-04-03"
pages_build_output_dir = "public"

# Production Environment Configuration
[env.production]
[[env.production.d1_databases]]
binding = "NATALIEWINTERS_DB"
database_name = "nataliewinters-db"
database_id = "67d2b960-fbe6-4451-b837-f88de68d2036"

# Development Environment Configuration
[env.development]
[[env.development.d1_databases]]
binding = "NATALIEWINTERS_DB"
database_name = "nataliewinters-db-dev"
database_id = "4e7cda13-39dd-430c-8c1c-29858789ddec"
