# Pages configuration
name = "natalie-winters-prod-this"  # Primary project name (production)
compatibility_date = "2024-04-03"
pages_build_output_dir = "public"

# Production Environment Configuration
[env.production]
[[env.production.d1_databases]]
binding = "NATALIEWINTERS_DB"
database_name = "nataliewinters-db"
database_id = "67d2b960-fbe6-4451-b837-f88de68d2036"

# Preview Environment Configuration (for non-production branches)
[env.preview]
[[env.preview.d1_databases]]
binding = "NATALIEWINTERS_DB"
database_name = "nataliewinters-db-dev"
database_id = "ad356616-d8f8-4bf8-8d41-63daf8601fab"
