name = "business-directory"
account_id = "0ac8cf282bbdc382ef6afb38b2ca79c7"
main = "worker.js"
compatibility_date = "2025-03-29"

[site]
bucket = "./public"

[[kv_namespaces]]
binding = "DIRECTORY_DATA"
id = "42c56c003c454a42a03f1b1fdaa8313f" 